version: "3"
services:
    app:
        image: awesome/backend
        # restart: always
        build:
          context: ./packages/server
          dockerfile: ./nestjs.dockerfile
        ports:
            - "3000:3000"
        stdin_open: true
        tty: true
        depends_on:
            - db
        networks:
            - default
            - our_net
        links:
            - "db"
            # - "db:database"
            # - "redis"
        # network_mode: "host"
    db:
        image: postgres:latest
        container_name: postgres
        # restart: always
        expose:
            - 5432
        # ports:
        #     - "5432:5432"
        environment:
            POSTGRES_USER: "dashBoard"
            POSTGRES_PASSWORD: "dashBoard"
        stdin_open: true
        tty: true
        networks:
            - default
            - our_net
        # network_mode: "host"
        # volumes:
        #     - D:/postgresql/data/:/var/lib/postgresql/data
networks:
  our_net:
    driver: bridge
