version: "3"
services:
    # app:
    #     image: awesome/backend
    #     restart: always
    #     build:
    #       context: .
    #       dockerfile: ./nestjs.dockerfile
    #     ports:
    #         - "3000:3000"
    #     stdin_open: true
    #     tty: true
    #     depends_on:
    #         - db
    #     networks:
    #         - default
    #         - our_net
    #     links:
    #         - "db"
        # network_mode: "host"
    db:
        image: postgres:latest
        container_name: postgres
        restart: always
        # expose:
        #     - 5432
        ports:
            - "5432:5432"
        environment:
            POSTGRES_USER: "postgres"
            POSTGRES_PASSWORD: "postgres"
        stdin_open: true
        tty: true
        networks:
            - default
            - our_net
        shm_size: "1g"
        # network_mode: "host"
        # volumes:
        #     - D:/postgresql/data/:/var/lib/postgresql/data
networks:
  our_net:
    driver: bridge
