version: "3"
services:
    # app:
    #     image: awesome/database
    #     # restart: always
    #     build:
    #       context: .
    #       dockerfile: ./nestjs.dockerfile
    #     ports:
    #         - "3000:3000"
    #     stdin_open: true
    #     tty: true
    db:
        image: postgres:latest
        container_name: postgres
        # restart: always
        ports:
            - "5432:5432"
        environment:
            POSTGRES_USER: "dashBoard"
            POSTGRES_PASSWORD: "dashBoard"
        # volumes:
        #     - D:/postgresql/data/:/var/lib/postgresql/data