export const tableName = {
  user: '학사정보',
  userPersonalInformation: '인적정보',
  userCourseExtension: '과정연장',
  userLeaveOfAbsence: '휴학',
  userBlackhole: 'BLACKHOLE',
  userInterruptionOfCourse: '과정중단',
  userLearningDataAPI: '학습데이터(API)',
  userLoyaltyManagement: '로열티 관리',
  userEmploymentStatus: '취업현황',
  userHrdNetUtilizeConsent: 'HRD-Net 동의',
  userHrdNetUtilize: 'HRD-Net_data',
  userOtherEmploymentStatus: '취업_기타수집_data',
  userEducationFundState: '지원금 관리',
  userComputationFund: '지원금 산정',
  userAccessCardInformation: '출입카드_info',
  userOtherInformation: '기타정보',
  userLapiscineInformation: 'La Piscine',
};
