name: common lint test

on:
  push:
    branches: [ "*" ]
  pull_request:
    branches: [ "main" ]

jobs:
  common-lint:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'yarn'

    - name: install & lint
      env:
          NODE_OPTIONS: '--max_old_space_size=4096'
      run: |
        yarn install --frozen-lockfile

    - name: lint
      env:
          NODE_OPTIONS: '--max_old_space_size=4096'
      run: |
        yarn lint

